M/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace= 'posts')),
    path('account/', include('account.urls', namespace = 'account')),


]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns =[
    path('login/', views.user_login, name = 'login'),
    path('register/', views.user_register, name ='register'),
    path('logout/', views.user_logout, name = 'logout'),
    path('dashboard/<int:user_id>', views.user_dashboard, name = 'dashboard')

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns =[
        path('', views.all_posts, name='all_posts'),
        path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name= 'post_detail'),
        path('add_post/<int:user_id>/', views.add_post, name = 'add_post'),

]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        return self.user.username


def save_profile(sender, **kwargs):
    if kwargs['created']:
        p1 = Profile(user=kwargs['instance'])
        p1.save()



post_save.connect(save_profile, sender=User)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
     user = models.ForeignKey(User, on_delete=models.CASCADE)
     body = models.TextField(max_length=500)
     slug = models.SlugField(max_length=200)
     created = models.DateTimeField(auto_now_add=True)


     def __str__(self):
        return f'{self.user} - {self.body[:30]}'

     def get_absolute_url(self):
      return reverse('posts:post_detail', args=[ self.created.year, self.created.month, self.created.day, self.slug])

account/forms.py
from django import forms

messages = {
    'required': 'این فیلد اجباری است',
    'invalid':'لطفا یک ایمیل معتبر وارد کنید',
    'max-length':'تعداد کاراکتر ها بیشتر از حد مجاز است'
}



class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    password = forms.CharField(max_length=40, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))

class UserRegistrationForm(forms.Form):
    username = forms.CharField(error_messages=messages,max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    email = forms.EmailField(error_messages=messages,max_length=50, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password = forms.CharField(error_messages=messages, max_length=40, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

posts/forms.py
from django import forms
from .models import Post


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserRegistrationForm ,UserLoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from posts.models import Post
from django.contrib.auth.decorators import login_required



def user_login(request):
    next = request.GET.get('next')
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'] , password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you logged in successfully', 'success')
                if next:
                     return redirect(next)
                return redirect('posts:all_posts')
            else:
                messages.error(request, 'wrong username or password', 'warning')
    else:
        form = UserLoginForm()
    return render(request, 'account/login.html', {'form':form})

def user_register(request):
    if request.method == 'POST':
        form =UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(cd['username'], cd['email'], cd['password'])
            login(request, user)
            messages.success(request, 'you registered  successfully', 'success')
            return redirect('posts:all_posts')
        else:
            messages.error(request, 'wrong username or password', 'warning')
    else:
        form = UserRegistrationForm()
    return render(request, 'account/register.html', {'form':form})

@login_required
def user_logout(request):
    logout(request)
    messages.success(request, 'you logged out successfully', 'success')
    return redirect('posts:all_posts')

@login_required
def user_dashboard(request, user_id):
    user = get_object_or_404(User, id=user_id)
    posts = Post.objects.filter(user=user)
    self_dash = False
    if request.user.id == user_id :
        self_dash = True
    return render(request, 'account/dashboard.html', {'user': user, 'posts': posts, 'self_dash': self_dash})

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from.models import Post
from .forms import AddPostForm
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required

def all_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts/all_posts.html', {'posts': posts})

def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, created__year=year, created__month=month, created__day=day, slug=slug)
    return render(request, 'posts/post_detail.html', {'post': post})

@login_required
def add_post(request, user_id):
    if request.user.id == user_id:
       if request.method == 'POST':
         form = AddPostForm(request.POST)
         if form.is_valid():
             new_post= form.save(commit=False)
             new_post.user = request.user
             new_post.slug = slugify(form.cleaned_data['body'][:30])
             new_post.save()
             messages.success(request, 'your post submitted', 'success')
         return redirect('account:dashboard', user_id)

       else:
         form = AddPostForm()
       return render(request, 'posts/add_post.html', {'form': form})
    else:
        return redirect('posts:all_posts')

posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block content %}
   <form action="" , method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
       <input type ="submit" value="Add Post"  class = "btn btn-primary">

   </form>

{% endblock %}

posts/templates/posts/all_posts.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}
    {% for post in posts %}
         <div class ="card"><br/>
             <p class = "card-header" ><a href="{% url 'account:dashboard' post.user.id %}">{{ post.user }}</a></p>
             <p class = "card-body"><a href = "{{ post.get_absolute_url }}">{{ post.body }}</a></p>

         </div><br/>

    {% endfor %}
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
      {% if request.user.id_authenticated and


      <p>{{ post.user }} | {{ post.created|date }}</p>
      <p>{{ post.body }}</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    {% include 'inc/navbar.html' %}
    <div class ="jumborton">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
   {% for message in messages %}
      <p class ="alert alert-{{ message.tags}}">{{message}}</p>
   {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'posts:all_posts' %}">Home</a>
          {%if request.user.is_authenticated %}
          <a class="nav-item nav-link active" href="{% url 'account:logout' %}">Logout</a>
          {% else  %}
          <a class="nav-item nav-link active" href="{% url 'account:login' %}">Login</a>
          <a class="nav-item nav-link active" href="{% url 'account:register' %}">Register</a>
          {% endif %}

      </div>

</nav>